Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,27 +16,22 @@ on:
         description: 'OrangeFox Device Tree'
         required: true
         default: 'https://github.com/secr5t/device_oppo_CPH2269/'
-        type: string
       DEVICE_TREE_BRANCH:
         description: 'OrangeFox Device Tree Branch'
         required: true
         default: 'fox-12.1'
-        type: string
       DEVICE_PATH:
         description: 'Device Tree Path'
         required: true
         default: 'device/oppo/CPH2269'
-        type: string
       DEVICE_NAME:
         description: 'Device Codename'
         required: true
         default: 'CPH2269'
-        type: string
       MAKEFILE_NAME:
         description: 'Makefile Name (excluding .mk extension, Example: twrp_codename)'
         required: true
         default: 'twrp_CPH2269'
-        type: string
       BUILD_TARGET:
         description: 'Build Target'
         required: true
@@ -53,147 +48,123 @@ jobs:
     permissions:
       contents: write
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+    - name: Checkout
+      uses: actions/checkout@v4
+                
+    - name: Clean-up
+      uses: rokibhasansagar/slimhub_actions@main
 
-      - name: Free Disk Space
-        run: |
-          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY"
-          sudo apt-get clean
+    - name: Swap Space
+      uses: pierotofy/set-swap-space@master
+      with:
+        swap-size-gb: 24
+      
+    - name: Build Environment
+      run: |
+        sudo apt-get update && sudo apt-get install -y aria2 git jq curl
+        git clone https://gitlab.com/OrangeFox/misc/scripts.git -b master
+        cd scripts
+        sudo bash setup/android_build_env.sh
 
-      - name: Swap Space
-        uses: pierotofy/set-swap-space@master
-        with:
-          swap-size-gb: 24
+    - name: Set-up Manifest
+      run: |
+        mkdir -p "${GITHUB_WORKSPACE}/OrangeFox"
+        cd "${GITHUB_WORKSPACE}/OrangeFox"
+        git config --global user.name "${{ github.actor }}"
+        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
+        git clone https://gitlab.com/OrangeFox/sync.git -b master
+        cd sync
+        ./orangefox_sync.sh --branch "${{ inputs.MANIFEST_BRANCH }}" --path "${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}"
 
-      - name: Build Environment
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y aria2 git jq curl ccache
-          git clone https://gitlab.com/OrangeFox/misc/scripts.git -b master --depth=1
-          cd scripts
-          sudo bash setup/android_build_env.sh
+    - name: Clone Device Tree
+      run: |
+        cd "${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}"
+        git clone "${{ inputs.DEVICE_TREE }}" -b "${{ inputs.DEVICE_TREE_BRANCH }}" "./${{ inputs.DEVICE_PATH }}"
+        cd "./${{ inputs.DEVICE_PATH }}"
+        
+        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
+        echo "SHORT_COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+        echo "COMMIT_TITLE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV
+        echo "COMMIT_DATE=$(git log -1 --date=format:%Y-%m-%d --pretty=%cd)" >> $GITHUB_ENV
 
-      - name: Setup CCache
-        uses: actions/cache@v4
-        with:
-          path: ~/.ccache
-          key: ccache-${{ inputs.MANIFEST_BRANCH }}-${{ inputs.DEVICE_NAME }}-${{ github.run_id }}
-          restore-keys: |
-            ccache-${{ inputs.MANIFEST_BRANCH }}-${{ inputs.DEVICE_NAME }}-
-            ccache-${{ inputs.MANIFEST_BRANCH }}-
+    - name: Get OrangeFox Recovery Commit
+      run: |
+        cd "${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/bootable/recovery"
 
-      - name: Set-up Manifest
-        run: |
-          mkdir -p "${GITHUB_WORKSPACE}/OrangeFox"
-          cd "${GITHUB_WORKSPACE}/OrangeFox"
-          git config --global user.name "${{ github.actor }}"
-          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
-          git clone https://gitlab.com/OrangeFox/sync.git -b master --depth=1
-          cd sync
-          ./orangefox_sync.sh --branch "${{ inputs.MANIFEST_BRANCH }}" --path "${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}"
+        echo "OF_COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
+        echo "OF_SHORT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+        echo "OF_COMMIT_TITLE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV
+        echo "OF_COMMIT_DATE=$(git log -1 --date=format:%Y-%m-%d --pretty=%cd)" >> $GITHUB_ENV
 
-      - name: Clone Device Tree
-        run: |
-          cd "${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}"
-          git clone "${{ inputs.DEVICE_TREE }}" -b "${{ inputs.DEVICE_TREE_BRANCH }}" --depth=1 "./${{ inputs.DEVICE_PATH }}"
-          cd "./${{ inputs.DEVICE_PATH }}"
-          
-          echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
-          echo "SHORT_COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
-          echo "COMMIT_TITLE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV
-          echo "COMMIT_DATE=$(git log -1 --date=format:%Y-%m-%d --pretty=%cd)" >> $GITHUB_ENV
+    - name: Set Build Date
+      run: |
+        echo "BUILD_DATE=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
 
-      - name: Get OrangeFox Recovery Commit
-        run: |
-          cd "${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/bootable/recovery"
+    - name: Building OrangeFox
+      run: |
+        cd "${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}"
+        
+        set +e
+        source build/envsetup.sh
+        set -e
+        
+        export ALLOW_MISSING_DEPENDENCIES=true
+        
+        if [ "${{ inputs.MANIFEST_BRANCH }}" = "14.1" ]; then
+          LUNCH_TARGET="${{ inputs.MAKEFILE_NAME }}-ap2a-eng"
+        else
+          LUNCH_TARGET="${{ inputs.MAKEFILE_NAME }}-eng"
+        fi
 
-          echo "OF_COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
-          echo "OF_SHORT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
-          echo "OF_COMMIT_TITLE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV
-          echo "OF_COMMIT_DATE=$(git log -1 --date=format:%Y-%m-%d --pretty=%cd)" >> $GITHUB_ENV
+        lunch "$LUNCH_TARGET" || { echo "Lunch failed"; exit 1; }
+        
+        make clean
+        
+        mka adbd "${{ inputs.BUILD_TARGET }}image"
 
-      - name: Set Build Timers
-        run: |
-          echo "BUILD_START=$(date +%s)" >> $GITHUB_ENV
-          echo "BUILD_DATE=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
-          echo "BUILD_DATE_PRETTY=$(date -u +'%d %b %Y, %H:%M UTC')" >> $GITHUB_ENV
+    - name: Rename Build Outputs
+      run: |
+        cd "${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}"
+        
+        for f in OrangeFox*.img; do
+          [ -e "$f" ] && mv "$f" "${f%.img}-${{ env.BUILD_DATE }}.img"
+        done
+        
+        for f in OrangeFox*.zip; do
+          [ -e "$f" ] && mv "$f" "${f%.zip}-${{ env.BUILD_DATE }}.zip"
+        done
 
-      - name: Building OrangeFox
-        run: |
-          cd "${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}"
-          
-          export USE_CCACHE=1
-          export CCACHE_EXEC=/usr/bin/ccache
-          export CCACHE_DIR="$HOME/.ccache"
-          export CCACHE_COMPRESS=1
-          export CCACHE_COMPRESSLEVEL=6
-          ccache -M 15G
-          ccache -z
-          
-          set +e
-          source build/envsetup.sh
-          set -e
-          
-          export ALLOW_MISSING_DEPENDENCIES=true
-          
-          if [ "${{ inputs.MANIFEST_BRANCH }}" = "14.1" ]; then
-            LUNCH_TARGET="${{ inputs.MAKEFILE_NAME }}-ap2a-eng"
-          else
-            LUNCH_TARGET="${{ inputs.MAKEFILE_NAME }}-eng"
-          fi
+    - name: Create Release Notes
+      run: |
+        cat <<EOF > release_notes.md
+        OrangeFox Branch: ${{ inputs.MANIFEST_BRANCH }}
 
-          lunch "$LUNCH_TARGET" || { echo "Lunch failed"; exit 1; }
-          
-          make clean
-          
-          mka -j$(nproc) adbd "${{ inputs.BUILD_TARGET }}image"
-          
-          ccache -s
+        Device: ${{ inputs.DEVICE_NAME }}
+        Image Build Target: ${{ inputs.BUILD_TARGET }}
+        
+        Device Tree Repo: [Device Tree](${{ inputs.DEVICE_TREE }})
+        Device Tree Branch: ${{ inputs.DEVICE_TREE_BRANCH }}
+        
+        OrangeFox Recovery Commit:
+        [${{ env.OF_SHORT_COMMIT }}](https://gitlab.com/OrangeFox/bootable/Recovery/-/commit/${{ env.OF_COMMIT_ID }}) - ${{ env.OF_COMMIT_TITLE }} (${{ env.OF_COMMIT_DATE }})
 
-      - name: Rename Build Outputs
-        run: |
-          cd "${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}"
-          
-          for f in OrangeFox*.img; do
-            [ -e "$f" ] && mv "$f" "${f%.img}-${{ env.BUILD_DATE }}.img"
-          done
-          
-          for f in OrangeFox*.zip; do
-            [ -e "$f" ] && mv "$f" "${f%.zip}-${{ env.BUILD_DATE }}.zip"
-          done
+        Device Tree Commit:
+        [${{ env.SHORT_COMMIT_ID }}](${{ inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) - ${{ env.COMMIT_TITLE }} (${{ env.COMMIT_DATE }})
+        EOF
 
-      - name: Create Release Notes
-        run: |
-          printf "OrangeFox Branch: %s\n\nDevice: %s\nImage Build Target: %s\n\nDevice Tree Repo: [Device Tree](%s)\nDevice Tree Branch: %s\n\nOrangeFox Recovery Commit:\n[%s](https://gitlab.com/OrangeFox/bootable/Recovery/-/commit/%s) - %s (%s)\n\nDevice Tree Commit:\n[%s](%s/commit/%s) - %s (%s)\n" \
-            "${{ inputs.MANIFEST_BRANCH }}" \
-            "${{ inputs.DEVICE_NAME }}" \
-            "${{ inputs.BUILD_TARGET }}" \
-            "${{ inputs.DEVICE_TREE }}" \
-            "${{ inputs.DEVICE_TREE_BRANCH }}" \
-            "${{ env.OF_SHORT_COMMIT }}" \
-            "${{ env.OF_COMMIT_ID }}" \
-            "${{ env.OF_COMMIT_TITLE }}" \
-            "${{ env.OF_COMMIT_DATE }}" \
-            "${{ env.SHORT_COMMIT_ID }}" \
-            "${{ inputs.DEVICE_TREE }}" \
-            "${{ env.COMMIT_ID }}" \
-            "${{ env.COMMIT_TITLE }}" \
-            "${{ env.COMMIT_DATE }}" > release_notes.md
+    - name: Upload to Release
+      uses: softprops/action-gh-release@v2
+      with:
+        files: |
+          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.img
+          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.zip
+        name: OrangeFox Recovery for ${{ inputs.DEVICE_NAME }} (${{ env.BUILD_DATE }}) (${{ env.SHORT_COMMIT_ID }})
+        tag_name: ${{ inputs.DEVICE_NAME }}-${{ env.BUILD_DATE }}
+        body_path: release_notes.md
+        prerelease: true
 
-      - name: Upload to Release
-        uses: softprops/action-gh-release@v2
-        with:
-          files: |
-            OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.img
-            OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.zip
-          name: OrangeFox Recovery for ${{ inputs.DEVICE_NAME }} (${{ env.BUILD_DATE }}) (${{ env.SHORT_COMMIT_ID }})
-          tag_name: ${{ inputs.DEVICE_NAME }}-${{ env.BUILD_DATE }}
-          body_path: release_notes.md
-          prerelease: true
-
-      - name: Send Notification to Telegram
-        run: |
+    - name: Send Notification to Telegram
+      run: |
           OUT_DIR="${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}"
           FILE=$(find "$OUT_DIR" -maxdepth 1 -type f -name "OrangeFox*.img" | head -n 1)
 
